
package view;
import controler.campotxtDouble;
import controler.campotxtMatricula;
        
public class telasBoletimUP extends javax.swing.JFrame {
    
    /**
     * Creates new form ExibitNotaPresenca
     */
    public telasBoletimUP() {
        initComponents();
        
        
        
        txtMatricula.setDocument(new campotxtMatricula());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        NotasPresenca = new javax.swing.JPanel();
        localizationPane2 = new javax.swing.JPanel();
        borderPane1 = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        tableAlunos = new javax.swing.JTable();
        RegistrarAluno = new javax.swing.JPanel();
        localizationPane = new javax.swing.JPanel();
        borderPane = new javax.swing.JPanel();
        formPane = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblMatricula1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        lblInsiraDados = new javax.swing.JLabel();
        RegistrarNota = new javax.swing.JPanel();
        localizationPane1 = new javax.swing.JPanel();
        borderPane2 = new javax.swing.JPanel();
        formPane1 = new javax.swing.JPanel();
        lblNome1 = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JTextField();
        lblMatricula2 = new javax.swing.JLabel();
        txtMatricula1 = new javax.swing.JTextField();
        lblMatricula3 = new javax.swing.JLabel();
        txtNome3 = new javax.swing.JTextField();
        btnEntrar1 = new javax.swing.JButton();
        lblMatricula4 = new javax.swing.JLabel();
        txtNome4 = new javax.swing.JTextField();
        lblInsiraDados1 = new javax.swing.JLabel();
        RegistrarPresenca = new javax.swing.JPanel();
        localizationPane3 = new javax.swing.JPanel();
        borderPane3 = new javax.swing.JPanel();
        scrollPanel2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        NotasPresenca.setBackground(new java.awt.Color(204, 255, 204));
        NotasPresenca.setLayout(new java.awt.GridBagLayout());

        localizationPane2.setOpaque(false);

        borderPane1.setBackground(new java.awt.Color(255, 255, 255));
        borderPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        borderPane1.setOpaque(false);

        tableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ALUNO", "RA", "Presença", "A1", "A2", "A3", "Média", "Situação"
            }
        ));
        scrollPanel.setViewportView(tableAlunos);
        if (tableAlunos.getColumnModel().getColumnCount() > 0) {
            tableAlunos.getColumnModel().getColumn(0).setPreferredWidth(300);
            tableAlunos.getColumnModel().getColumn(0).setHeaderValue("ALUNO");
            tableAlunos.getColumnModel().getColumn(1).setPreferredWidth(180);
            tableAlunos.getColumnModel().getColumn(1).setHeaderValue("Matricula");
            tableAlunos.getColumnModel().getColumn(2).setHeaderValue("03/06/2025");
            tableAlunos.getColumnModel().getColumn(3).setHeaderValue("04/06/2025");
            tableAlunos.getColumnModel().getColumn(4).setHeaderValue("05/06/2025");
            tableAlunos.getColumnModel().getColumn(5).setHeaderValue("A3");
            tableAlunos.getColumnModel().getColumn(6).setHeaderValue("Média");
            tableAlunos.getColumnModel().getColumn(7).setPreferredWidth(150);
            tableAlunos.getColumnModel().getColumn(7).setHeaderValue("Situação");
        }

        javax.swing.GroupLayout borderPane1Layout = new javax.swing.GroupLayout(borderPane1);
        borderPane1.setLayout(borderPane1Layout);
        borderPane1Layout.setHorizontalGroup(
            borderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        borderPane1Layout.setVerticalGroup(
            borderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout localizationPane2Layout = new javax.swing.GroupLayout(localizationPane2);
        localizationPane2.setLayout(localizationPane2Layout);
        localizationPane2Layout.setHorizontalGroup(
            localizationPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        localizationPane2Layout.setVerticalGroup(
            localizationPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, localizationPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(borderPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        NotasPresenca.add(localizationPane2, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Notas/Presença", NotasPresenca);

        RegistrarAluno.setBackground(new java.awt.Color(204, 255, 204));
        RegistrarAluno.setLayout(new java.awt.GridBagLayout());

        localizationPane.setOpaque(false);

        borderPane.setBackground(new java.awt.Color(255, 255, 255));
        borderPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        borderPane.setPreferredSize(new java.awt.Dimension(500, 543));

        formPane.setOpaque(false);

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNome.setToolTipText("Nome do Aluno");
        txtNome.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblMatricula.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMatricula.setText("E-mail");

        txtMatricula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtMatricula.setToolTipText("");
        txtMatricula.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        lblMatricula1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMatricula1.setText("Matrícula:");

        txtNome1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNome1.setToolTipText("Nome do Aluno");
        txtNome1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtNome1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNome1FocusGained(evt);
            }
        });
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(102, 255, 102));
        btnEntrar.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        btnEntrar.setText("Registrar Aluno");
        btnEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEntrar.setBorderPainted(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPaneLayout = new javax.swing.GroupLayout(formPane);
        formPane.setLayout(formPaneLayout);
        formPaneLayout.setHorizontalGroup(
            formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(lblMatricula)
                            .addComponent(txtMatricula))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricula1)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))))
            .addGroup(formPaneLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        formPaneLayout.setVerticalGroup(
            formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMatricula1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout borderPaneLayout = new javax.swing.GroupLayout(borderPane);
        borderPane.setLayout(borderPaneLayout);
        borderPaneLayout.setHorizontalGroup(
            borderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPaneLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(formPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        borderPaneLayout.setVerticalGroup(
            borderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(formPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout localizationPaneLayout = new javax.swing.GroupLayout(localizationPane);
        localizationPane.setLayout(localizationPaneLayout);
        localizationPaneLayout.setHorizontalGroup(
            localizationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        localizationPaneLayout.setVerticalGroup(
            localizationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 92, 56, 92);
        RegistrarAluno.add(localizationPane, gridBagConstraints);

        lblInsiraDados.setBackground(new java.awt.Color(230, 240, 240));
        lblInsiraDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/InsiraOsDados_resized.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 189, 0, 0);
        RegistrarAluno.add(lblInsiraDados, gridBagConstraints);

        jTabbedPane1.addTab("Registrar Aluno", RegistrarAluno);

        RegistrarNota.setBackground(new java.awt.Color(204, 255, 204));
        RegistrarNota.setLayout(new java.awt.GridBagLayout());

        localizationPane1.setOpaque(false);

        borderPane2.setBackground(new java.awt.Color(255, 255, 255));
        borderPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        borderPane2.setPreferredSize(new java.awt.Dimension(500, 543));

        formPane1.setOpaque(false);

        lblNome1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNome1.setText("Nota A1");

        txtNome2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNome2.setToolTipText("Nome do Aluno");
        txtNome2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtNome2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNome2FocusGained(evt);
            }
        });
        txtNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome2ActionPerformed(evt);
            }
        });

        lblMatricula2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMatricula2.setText("Nota A2");

        txtMatricula1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtMatricula1.setToolTipText("");
        txtMatricula1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatricula1ActionPerformed(evt);
            }
        });

        lblMatricula3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMatricula3.setText("Matrícula:");

        txtNome3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNome3.setToolTipText("Nome do Aluno");
        txtNome3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtNome3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNome3FocusGained(evt);
            }
        });
        txtNome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome3ActionPerformed(evt);
            }
        });

        btnEntrar1.setBackground(new java.awt.Color(102, 255, 102));
        btnEntrar1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        btnEntrar1.setText("Registrar Nota");
        btnEntrar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEntrar1.setBorderPainted(false);
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });

        lblMatricula4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMatricula4.setText("Nota A3");

        txtNome4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNome4.setToolTipText("Nome do Aluno");
        txtNome4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtNome4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNome4FocusGained(evt);
            }
        });
        txtNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPane1Layout = new javax.swing.GroupLayout(formPane1);
        formPane1.setLayout(formPane1Layout);
        formPane1Layout.setHorizontalGroup(
            formPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPane1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(formPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPane1Layout.createSequentialGroup()
                        .addGroup(formPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricula3)
                            .addComponent(lblNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formPane1Layout.createSequentialGroup()
                        .addGroup(formPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNome2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMatricula4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMatricula2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(txtNome3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE))))
            .addGroup(formPane1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnEntrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        formPane1Layout.setVerticalGroup(
            formPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMatricula3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMatricula2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMatricula4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnEntrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout borderPane2Layout = new javax.swing.GroupLayout(borderPane2);
        borderPane2.setLayout(borderPane2Layout);
        borderPane2Layout.setHorizontalGroup(
            borderPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPane2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(formPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        borderPane2Layout.setVerticalGroup(
            borderPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPane2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(formPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout localizationPane1Layout = new javax.swing.GroupLayout(localizationPane1);
        localizationPane1.setLayout(localizationPane1Layout);
        localizationPane1Layout.setHorizontalGroup(
            localizationPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        localizationPane1Layout.setVerticalGroup(
            localizationPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 92, 56, 92);
        RegistrarNota.add(localizationPane1, gridBagConstraints);

        lblInsiraDados1.setBackground(new java.awt.Color(230, 240, 240));
        lblInsiraDados1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/InsiraOsDados_resized.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 189, 0, 0);
        RegistrarNota.add(lblInsiraDados1, gridBagConstraints);

        jTabbedPane1.addTab("Registrar Nota", RegistrarNota);

        RegistrarPresenca.setBackground(new java.awt.Color(204, 255, 204));
        RegistrarPresenca.setLayout(new java.awt.GridBagLayout());

        localizationPane3.setOpaque(false);

        borderPane3.setBackground(new java.awt.Color(255, 255, 255));
        borderPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        borderPane3.setOpaque(false);

        scrollPanel2.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Matricula", "03/06/2025", "04/06/2025", "05/06/2025"
            }
        ));
        scrollPanel2.setViewportView(jTable1);

        javax.swing.GroupLayout borderPane3Layout = new javax.swing.GroupLayout(borderPane3);
        borderPane3.setLayout(borderPane3Layout);
        borderPane3Layout.setHorizontalGroup(
            borderPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        borderPane3Layout.setVerticalGroup(
            borderPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout localizationPane3Layout = new javax.swing.GroupLayout(localizationPane3);
        localizationPane3.setLayout(localizationPane3Layout);
        localizationPane3Layout.setHorizontalGroup(
            localizationPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        localizationPane3Layout.setVerticalGroup(
            localizationPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, localizationPane3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(borderPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RegistrarPresenca.add(localizationPane3, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Registrar Presença", RegistrarPresenca);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabPane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtNome1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNome1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1FocusGained

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtNome2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNome2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome2FocusGained

    private void txtNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome2ActionPerformed

    private void txtMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatricula1ActionPerformed

    private void txtNome3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNome3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome3FocusGained

    private void txtNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome3ActionPerformed

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    private void txtNome4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNome4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome4FocusGained

    private void txtNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome4ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telasBoletimUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NotasPresenca;
    private javax.swing.JPanel RegistrarAluno;
    private javax.swing.JPanel RegistrarNota;
    private javax.swing.JPanel RegistrarPresenca;
    private javax.swing.JPanel borderPane;
    private javax.swing.JPanel borderPane1;
    private javax.swing.JPanel borderPane2;
    private javax.swing.JPanel borderPane3;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JPanel formPane;
    private javax.swing.JPanel formPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInsiraDados;
    private javax.swing.JLabel lblInsiraDados1;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMatricula1;
    private javax.swing.JLabel lblMatricula2;
    private javax.swing.JLabel lblMatricula3;
    private javax.swing.JLabel lblMatricula4;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JPanel localizationPane;
    private javax.swing.JPanel localizationPane1;
    private javax.swing.JPanel localizationPane2;
    private javax.swing.JPanel localizationPane3;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JScrollPane scrollPanel2;
    private javax.swing.JTable tableAlunos;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatricula1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNome2;
    private javax.swing.JTextField txtNome3;
    private javax.swing.JTextField txtNome4;
    // End of variables declaration//GEN-END:variables
}
