
package view;
import controler.campotxtDouble;
import controler.campotxtMatricula;
        
public class telasBoletimUP extends javax.swing.JFrame {
    
    /**
     * Creates new form ExibitNotaPresenca
     */
    public telasBoletimUP() {
        initComponents();
        
        txtAvaliacao1.setDocument(new campotxtDouble());
        txtAvaliacao2.setDocument(new campotxtDouble());
        txtAvaliacao3.setDocument(new campotxtDouble());
        
        txtMatricula.setDocument(new campotxtMatricula());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        localizationPane1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NotasPresenca = new javax.swing.JPanel();
        localizationPane2 = new javax.swing.JPanel();
        borderPane1 = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        tableAlunos = new javax.swing.JTable();
        RegistrarAluno = new javax.swing.JPanel();
        localizationPane = new javax.swing.JPanel();
        borderPane = new javax.swing.JPanel();
        lblInsiraDados = new javax.swing.JLabel();
        formPane = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblAvaliacao1 = new javax.swing.JLabel();
        txtAvaliacao1 = new javax.swing.JTextField();
        lblAvaliacao2 = new javax.swing.JLabel();
        txtAvaliacao2 = new javax.swing.JTextField();
        lblAvaliacao3 = new javax.swing.JLabel();
        txtAvaliacao3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        RegistrarPresenca = new javax.swing.JPanel();
        localizationPane3 = new javax.swing.JPanel();
        borderPane3 = new javax.swing.JPanel();
        scrollPanel2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        inicio.setBackground(new java.awt.Color(204, 255, 204));

        localizationPane1.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BoletimUpIcon.png"))); // NOI18N

        javax.swing.GroupLayout localizationPane1Layout = new javax.swing.GroupLayout(localizationPane1);
        localizationPane1.setLayout(localizationPane1Layout);
        localizationPane1Layout.setHorizontalGroup(
            localizationPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, localizationPane1Layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36))
        );
        localizationPane1Layout.setVerticalGroup(
            localizationPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(634, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backgroundLoginCadastro.png"))); // NOI18N

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(localizationPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inicioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(localizationPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inicioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Início", inicio);

        NotasPresenca.setBackground(new java.awt.Color(204, 255, 204));
        NotasPresenca.setLayout(new java.awt.GridBagLayout());

        localizationPane2.setOpaque(false);

        borderPane1.setBackground(new java.awt.Color(255, 255, 255));
        borderPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        borderPane1.setOpaque(false);

        tableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ALUNO", "RA", "Presença", "A1", "A2", "A3", "Média", "Situação"
            }
        ));
        scrollPanel.setViewportView(tableAlunos);
        if (tableAlunos.getColumnModel().getColumnCount() > 0) {
            tableAlunos.getColumnModel().getColumn(0).setPreferredWidth(300);
            tableAlunos.getColumnModel().getColumn(0).setHeaderValue("ALUNO");
            tableAlunos.getColumnModel().getColumn(1).setPreferredWidth(180);
            tableAlunos.getColumnModel().getColumn(1).setHeaderValue("Matricula");
            tableAlunos.getColumnModel().getColumn(2).setHeaderValue("03/06/2025");
            tableAlunos.getColumnModel().getColumn(3).setHeaderValue("04/06/2025");
            tableAlunos.getColumnModel().getColumn(4).setHeaderValue("05/06/2025");
            tableAlunos.getColumnModel().getColumn(5).setHeaderValue("A3");
            tableAlunos.getColumnModel().getColumn(6).setHeaderValue("Média");
            tableAlunos.getColumnModel().getColumn(7).setPreferredWidth(150);
            tableAlunos.getColumnModel().getColumn(7).setHeaderValue("Situação");
        }

        javax.swing.GroupLayout borderPane1Layout = new javax.swing.GroupLayout(borderPane1);
        borderPane1.setLayout(borderPane1Layout);
        borderPane1Layout.setHorizontalGroup(
            borderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        borderPane1Layout.setVerticalGroup(
            borderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout localizationPane2Layout = new javax.swing.GroupLayout(localizationPane2);
        localizationPane2.setLayout(localizationPane2Layout);
        localizationPane2Layout.setHorizontalGroup(
            localizationPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        localizationPane2Layout.setVerticalGroup(
            localizationPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, localizationPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(borderPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        NotasPresenca.add(localizationPane2, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Notas/Presença", NotasPresenca);

        RegistrarAluno.setBackground(new java.awt.Color(204, 255, 204));
        RegistrarAluno.setLayout(new java.awt.GridBagLayout());

        localizationPane.setOpaque(false);

        borderPane.setBackground(new java.awt.Color(255, 255, 255));
        borderPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        borderPane.setOpaque(false);

        lblInsiraDados.setBackground(new java.awt.Color(230, 240, 240));
        lblInsiraDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/InsiraOsDados_resized.png"))); // NOI18N

        formPane.setOpaque(false);

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNome.setToolTipText("Nome do Aluno");
        txtNome.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblMatricula.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMatricula.setText("Matrícula:");

        txtMatricula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtMatricula.setToolTipText("");
        txtMatricula.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        lblAvaliacao1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAvaliacao1.setText("1º Avaliação:");

        txtAvaliacao1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAvaliacao1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAvaliacao1.setToolTipText("");
        txtAvaliacao1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtAvaliacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvaliacao1ActionPerformed(evt);
            }
        });

        lblAvaliacao2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAvaliacao2.setText("2º Avaliação:");

        txtAvaliacao2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAvaliacao2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAvaliacao2.setToolTipText("");
        txtAvaliacao2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtAvaliacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvaliacao2ActionPerformed(evt);
            }
        });

        lblAvaliacao3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAvaliacao3.setText("3º Avaliação:");

        txtAvaliacao3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAvaliacao3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAvaliacao3.setToolTipText("");
        txtAvaliacao3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtAvaliacao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvaliacao3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 133, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Registrar Aluno");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPaneLayout = new javax.swing.GroupLayout(formPane);
        formPane.setLayout(formPaneLayout);
        formPaneLayout.setHorizontalGroup(
            formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPaneLayout.createSequentialGroup()
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formPaneLayout.createSequentialGroup()
                                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMatricula)
                                    .addComponent(lblNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(formPaneLayout.createSequentialGroup()
                                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAvaliacao2)
                                    .addComponent(lblAvaliacao1)
                                    .addComponent(lblAvaliacao3))
                                .addGap(18, 18, 18)
                                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAvaliacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAvaliacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAvaliacao3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        formPaneLayout.setVerticalGroup(
            formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvaliacao1)
                    .addComponent(txtAvaliacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvaliacao2)
                    .addComponent(txtAvaliacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvaliacao3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvaliacao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout borderPaneLayout = new javax.swing.GroupLayout(borderPane);
        borderPane.setLayout(borderPaneLayout);
        borderPaneLayout.setHorizontalGroup(
            borderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPaneLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(borderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsiraDados, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        borderPaneLayout.setVerticalGroup(
            borderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPaneLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(lblInsiraDados)
                .addGap(18, 18, 18)
                .addComponent(formPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout localizationPaneLayout = new javax.swing.GroupLayout(localizationPane);
        localizationPane.setLayout(localizationPaneLayout);
        localizationPaneLayout.setHorizontalGroup(
            localizationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(borderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        localizationPaneLayout.setVerticalGroup(
            localizationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(75, 79, 51, 77);
        RegistrarAluno.add(localizationPane, gridBagConstraints);

        jTabbedPane1.addTab("Registrar Aluno", RegistrarAluno);

        RegistrarPresenca.setBackground(new java.awt.Color(204, 255, 204));
        RegistrarPresenca.setLayout(new java.awt.GridBagLayout());

        localizationPane3.setOpaque(false);

        borderPane3.setBackground(new java.awt.Color(255, 255, 255));
        borderPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        borderPane3.setOpaque(false);

        scrollPanel2.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Matricula", "03/06/2025", "04/06/2025", "05/06/2025"
            }
        ));
        scrollPanel2.setViewportView(jTable1);

        javax.swing.GroupLayout borderPane3Layout = new javax.swing.GroupLayout(borderPane3);
        borderPane3.setLayout(borderPane3Layout);
        borderPane3Layout.setHorizontalGroup(
            borderPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        borderPane3Layout.setVerticalGroup(
            borderPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout localizationPane3Layout = new javax.swing.GroupLayout(localizationPane3);
        localizationPane3.setLayout(localizationPane3Layout);
        localizationPane3Layout.setHorizontalGroup(
            localizationPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(localizationPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        localizationPane3Layout.setVerticalGroup(
            localizationPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, localizationPane3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(borderPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RegistrarPresenca.add(localizationPane3, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Registrar Presença", RegistrarPresenca);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabPane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtAvaliacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvaliacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvaliacao1ActionPerformed

    private void txtAvaliacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvaliacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvaliacao2ActionPerformed

    private void txtAvaliacao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvaliacao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvaliacao3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telasBoletimUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telasBoletimUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NotasPresenca;
    private javax.swing.JPanel RegistrarAluno;
    private javax.swing.JPanel RegistrarPresenca;
    private javax.swing.JPanel borderPane;
    private javax.swing.JPanel borderPane1;
    private javax.swing.JPanel borderPane3;
    private javax.swing.JPanel formPane;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvaliacao1;
    private javax.swing.JLabel lblAvaliacao2;
    private javax.swing.JLabel lblAvaliacao3;
    private javax.swing.JLabel lblInsiraDados;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel localizationPane;
    private javax.swing.JPanel localizationPane1;
    private javax.swing.JPanel localizationPane2;
    private javax.swing.JPanel localizationPane3;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JScrollPane scrollPanel2;
    private javax.swing.JTable tableAlunos;
    private javax.swing.JTextField txtAvaliacao1;
    private javax.swing.JTextField txtAvaliacao2;
    private javax.swing.JTextField txtAvaliacao3;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
