
package view;

import controler.LoginControler;
import javax.swing.JOptionPane;
import controler.RelatorioAlunoControler;
import model.RelatorioAluno;

public class TelaAluno extends javax.swing.JFrame {
    private String emailAluno;
    
    public TelaAluno(String emailAluno){
        this.emailAluno = emailAluno;
        initComponents();
        carregarDadosAluno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelInfoAluno = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextPane();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextPane();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextPane();
        panelPresença = new javax.swing.JPanel();
        lblPresenca = new javax.swing.JLabel();
        txtPresenca = new javax.swing.JTextField();
        progressBarPresenca = new javax.swing.JProgressBar();
        panelNotas = new javax.swing.JPanel();
        lblQuadroNotas = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        txtA1 = new javax.swing.JTextField();
        lblA2 = new javax.swing.JLabel();
        txtA2 = new javax.swing.JTextField();
        lblA3 = new javax.swing.JLabel();
        txtA3 = new javax.swing.JTextField();
        panelQuadroNotas = new javax.swing.JPanel();
        lblSituacao = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JTextField();
        btnVoltarLogin = new javax.swing.JButton();
        lblAreaAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(1280, 720));

        panelInfoAluno.setBackground(new java.awt.Color(255, 255, 255));
        panelInfoAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblNome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.setEditable(false);

        lblMatricula.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMatricula.setText("Matricula:");

        txtMatricula.setEditable(false);

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblEmail.setText("E-mail:");

        txtEmail.setEditable(false);

        panelPresença.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPresença.setOpaque(false);

        lblPresenca.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPresenca.setText("Presença");

        txtPresenca.setEditable(false);
        txtPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPresençaLayout = new javax.swing.GroupLayout(panelPresença);
        panelPresença.setLayout(panelPresençaLayout);
        panelPresençaLayout.setHorizontalGroup(
            panelPresençaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresençaLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(panelPresençaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPresenca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPresençaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBarPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panelPresençaLayout.setVerticalGroup(
            panelPresençaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresençaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPresenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBarPresenca, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(txtPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelInfoAlunoLayout = new javax.swing.GroupLayout(panelInfoAluno);
        panelInfoAluno.setLayout(panelInfoAlunoLayout);
        panelInfoAlunoLayout.setHorizontalGroup(
            panelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPresença, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInfoAlunoLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoAlunoLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(lblEmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoAlunoLayout.createSequentialGroup()
                        .addComponent(lblMatricula)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatricula)))
                .addContainerGap())
        );
        panelInfoAlunoLayout.setVerticalGroup(
            panelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAlunoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(panelPresença, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        panelNotas.setBackground(new java.awt.Color(255, 255, 255));
        panelNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblQuadroNotas.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblQuadroNotas.setText("Quadro de notas");

        lblA1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblA1.setText("Avaliação 1:");

        txtA1.setEditable(false);
        txtA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA1ActionPerformed(evt);
            }
        });

        lblA2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblA2.setText("Avaliação 2:");

        txtA2.setEditable(false);
        txtA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA2ActionPerformed(evt);
            }
        });

        lblA3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblA3.setText("Avaliação 3:");

        txtA3.setEditable(false);
        txtA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA3ActionPerformed(evt);
            }
        });

        panelQuadroNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelQuadroNotas.setOpaque(false);

        lblSituacao.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSituacao.setText("Situação");

        txtSituacao.setEditable(false);
        txtSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSituacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuadroNotasLayout = new javax.swing.GroupLayout(panelQuadroNotas);
        panelQuadroNotas.setLayout(panelQuadroNotasLayout);
        panelQuadroNotasLayout.setHorizontalGroup(
            panelQuadroNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuadroNotasLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(panelQuadroNotasLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblSituacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelQuadroNotasLayout.setVerticalGroup(
            panelQuadroNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuadroNotasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelNotasLayout = new javax.swing.GroupLayout(panelNotas);
        panelNotas.setLayout(panelNotasLayout);
        panelNotasLayout.setHorizontalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelQuadroNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotasLayout.createSequentialGroup()
                            .addComponent(lblA2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtA2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotasLayout.createSequentialGroup()
                            .addComponent(lblA3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtA3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotasLayout.createSequentialGroup()
                            .addComponent(lblA1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblQuadroNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelNotasLayout.setVerticalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblQuadroNotas)
                .addGap(73, 73, 73)
                .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA1)
                    .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA2)
                    .addComponent(txtA2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtA3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblA3))
                .addGap(29, 29, 29)
                .addComponent(panelQuadroNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVoltarLogin.setBackground(new java.awt.Color(102, 255, 102));
        btnVoltarLogin.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        btnVoltarLogin.setText("voltar para login");
        btnVoltarLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnVoltarLogin.setBorderPainted(false);
        btnVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInfoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAreaAluno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAreaAluno)
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void carregarDadosAluno() {
        RelatorioAlunoControler controler = new RelatorioAlunoControler();
        RelatorioAluno aluno = controler.buscarRelatorioPorEmail(emailAluno);

        if (aluno != null) {
            txtNome.setText(aluno.getNome());
            txtMatricula.setText(String.valueOf(aluno.getMatricula()));
            txtEmail.setText(emailAluno);

            txtA1.setText(String.valueOf(aluno.getAvaliacao1()));
            txtA2.setText(String.valueOf(aluno.getAvaliacao2()));
            txtA3.setText(String.valueOf(aluno.getAvaliacao3()));
            
            txtSituacao.setText(aluno.getSituacao());
            
            double presenca = aluno.getMediaPresenca(); 

            txtPresenca.setText(presenca + " %");
            progressBarPresenca.setValue((int) presenca);
            progressBarPresenca.setStringPainted(true); 
            progressBarPresenca.setString(presenca + "% Presença"); 

        } else {
            JOptionPane.showMessageDialog(this, "Dados do aluno não encontrados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void txtA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA1ActionPerformed

    private void txtA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA2ActionPerformed

    private void txtA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA3ActionPerformed

    private void txtPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresencaActionPerformed

    private void txtSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSituacaoActionPerformed

    private void btnVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLoginActionPerformed
        int resposta = JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja sair da sua conta?",
            "Confirmação de Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {

            Login telaLogin = new Login();
            telaLogin.setVisible(true);
            this.dispose(); 
        }
    }//GEN-LAST:event_btnVoltarLoginActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblAreaAluno;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPresenca;
    private javax.swing.JLabel lblQuadroNotas;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JPanel panelInfoAluno;
    private javax.swing.JPanel panelNotas;
    private javax.swing.JPanel panelPresença;
    private javax.swing.JPanel panelQuadroNotas;
    private javax.swing.JProgressBar progressBarPresenca;
    private javax.swing.JTextField txtA1;
    private javax.swing.JTextField txtA2;
    private javax.swing.JTextField txtA3;
    private javax.swing.JTextPane txtEmail;
    private javax.swing.JTextPane txtMatricula;
    private javax.swing.JTextPane txtNome;
    private javax.swing.JTextField txtPresenca;
    private javax.swing.JTextField txtSituacao;
    // End of variables declaration//GEN-END:variables
}
